### ISSUE TITLE
Missing file "flow_barnes.log"

### ISSUE THREAD

**Issue by vatek1** [timfoil/PhotonicCoreSimulator#39]
As we cloned the project, it was discovered that it is not possible for it to work as coded. A remote file call to the previously mentioned log file causes analytic to fail. After a few hours of examining the call to log file found that file is not present in repository. It is a minor fix but mentioned file should be in repository so that build will function. Thanks!

**Comment by timfoil** [comment]
Thank you for bringing this to my attention. I have gone ahead and merged your pull request with the master branch of this repository. There are still some nasty connections between the depreciated gui and the core library of the project, I will try my best to resolve them. Again thank you for alerting me of this issue.

**Comment by vatek1** [comment]
Your welcome and thank you for your response so quickly. Dr. Zhang at UMES has a group researching the Simulator, they have only just begun but any help from yourself is greatly appreciated!
